name: dta
channels:
- pytorch
dependencies:
- python
- pytorch==1.13.0
- pytorch-cuda==11.7
- numpy
- psutil #5.9.0
- opencv
- pip
- pip:
  - atari-py
  - pyprind
  - protobuf
  - tensorflow
  - absl-py
  - gin-config
  - gym
  - tqdm
  - opencv-python
  - pillow
  - git+https://github.com/google/dopamine.git
